# user.cmake — persistent overrides applied AFTER MCC's generated rules.
# Included automatically by ../CMakeLists.txt if present.
#
# GCC honors the LAST -O flag on the command line, so appending -O3 here
# overrides the -O1 baked into .generated/rule.cmake without having to edit
# that file (which gets regenerated by MCC).

target_compile_options(ML_OV7670_GFX_default_default_XC32_compile     PRIVATE -O3)
target_compile_options(ML_OV7670_GFX_default_default_XC32_compile_cpp PRIVATE -O3)

# Verified harmless: __ARM_FEATURE_DSP=1 is auto-set by xc32-gcc on this
# part, so cmsis_gcc.h's SIMD intrinsics (pkhbt/smlad/smlald) are already
# active. ARM_MATH_DSP gates a different set of code paths in CMSIS-NN
# that aren't on TinyEngine's hot path; defining it costs nothing and
# unlocks the few places that do check it.
target_compile_definitions(ML_OV7670_GFX_default_default_XC32_compile     PRIVATE ARM_MATH_DSP ARM_MATH_LOOPUNROLL)
target_compile_definitions(ML_OV7670_GFX_default_default_XC32_compile_cpp PRIVATE ARM_MATH_DSP ARM_MATH_LOOPUNROLL)

# Match link-stage optimization to the compile stage. The exe target name
# has a regen-specific hash, so find it dynamically.
get_property(_all_targets DIRECTORY PROPERTY BUILDSYSTEM_TARGETS)
foreach(_tgt ${_all_targets})
    get_target_property(_type ${_tgt} TYPE)
    if(_type STREQUAL "EXECUTABLE")
        target_link_options(${_tgt} PRIVATE -O3)
    endif()
endforeach()
