"""
ConvertImagesToHex_VWW0.py

Pull a few VWW samples from an ImageFolder-style directory tree (subdirs
'person/' and 'non-person/' — the layout MCUNet's eval_tflite.py expects)
and emit a single C header containing them as int8 arrays plus a manifest.

Defaults to 64x64x3 to match this project's mcunet-vww0 model. Override
--width/--height for other MCUNet variants (vww1=80, vww2=144).

The model on the MCU loads each array directly into TinyEngine's input
buffer with memcpy and runs invoke(), so the per-pixel mapping must match
firmware-side rgb565_to_modelinput_vww:

    uint8 [0,255]  ->  int8 [-128,127]   via   (uint8 - 128)

Bilinear (not nearest) is used to mirror the training preprocessing in
mcunet/eval_tflite.py.

Usage:
  python ConvertImagesToHex_VWW0.py \
      --in-dir <path>/vww-minival/val \
      --n-per-class 3 \
      --out      ../My_MCC_Config/src/test_images.h
"""

import argparse
import re
from pathlib import Path

from PIL import Image
import numpy as np


CHANNELS = 3  # MCUNet VWW models are all RGB888


def safe_ident(name: str) -> str:
    return re.sub(r"[^A-Za-z0-9_]", "_", name).strip("_") or "img"


def load_int8(path: Path, width: int, height: int) -> np.ndarray:
    img = Image.open(path).convert("RGB").resize(
        (width, height), Image.BILINEAR
    )
    arr = np.asarray(img, dtype=np.int16) - 128
    return arr.astype(np.int8).flatten()


def emit_array(name: str, data: np.ndarray, fp) -> None:
    fp.write(f"static const int8_t {name}[{data.size}] = {{\n")
    for i in range(0, data.size, 12):
        chunk = data[i : i + 12]
        fp.write("    " + ", ".join(f"{int(v):4d}" for v in chunk) + ",\n")
    fp.write("};\n\n")


def collect(in_dir: Path, subdir: str, n: int) -> list:
    folder = in_dir / subdir
    if not folder.is_dir():
        raise SystemExit(f"missing class dir: {folder}")
    files = sorted(
        p for p in folder.iterdir()
        if p.suffix.lower() in {".jpg", ".jpeg", ".png", ".bmp"}
    )
    if len(files) < n:
        raise SystemExit(
            f"only {len(files)} images in {folder}, requested {n}"
        )
    # Deterministic selection: evenly spaced across the sorted list to get
    # a spread of scenes, not just the first N alphabetical neighbours.
    step = len(files) // n
    return [files[i * step] for i in range(n)]


def main() -> None:
    p = argparse.ArgumentParser()
    p.add_argument(
        "--in-dir", required=True, type=Path,
        help="ImageFolder root with subdirs 'person/' and 'non-person/'",
    )
    p.add_argument("--n-per-class", type=int, default=3)
    p.add_argument("--out", required=True, type=Path)
    p.add_argument(
        "--width", type=int, default=64,
        help="Model input width (VWW0=64, VWW1=80, VWW2=144; default 64)",
    )
    p.add_argument(
        "--height", type=int, default=64,
        help="Model input height (VWW0=64, VWW1=80, VWW2=144; default 64)",
    )
    p.add_argument(
        "--person-subdir", default="person",
        help="Subdir name for class 0 (default: person)",
    )
    p.add_argument(
        "--noperson-subdir", default="non-person",
        help="Subdir name for class 1 (default: non-person)",
    )
    args = p.parse_args()

    bytes_per_image = args.width * args.height * CHANNELS

    person_files = collect(args.in_dir, args.person_subdir, args.n_per_class)
    noperson_files = collect(args.in_dir, args.noperson_subdir, args.n_per_class)

    entries = []  # (c_array_name, source_path, expected_label_int)
    for i, f in enumerate(person_files):
        entries.append((f"test_img_person_{i:02d}", f, 0))
    for i, f in enumerate(noperson_files):
        entries.append((f"test_img_noperson_{i:02d}", f, 1))

    args.out.parent.mkdir(parents=True, exist_ok=True)
    with open(args.out, "w", encoding="utf-8") as fp:
        fp.write("/* Auto-generated by ML Model/ConvertImagesToHex.py — do not edit. */\n")
        fp.write(
            f"/* Layout: {args.height} rows x {args.width} cols x {CHANNELS} ch HWC int8. */\n"
        )
        fp.write("#ifndef TEST_IMAGES_H_\n")
        fp.write("#define TEST_IMAGES_H_\n\n")
        fp.write("#include <stdint.h>\n\n")

        for name, src, _label in entries:
            fp.write(f"/* source: {src.name} */\n")
            data = load_int8(src, args.width, args.height)
            assert data.size == bytes_per_image
            emit_array(name, data, fp)

        fp.write("typedef struct {\n")
        fp.write("    const int8_t *data;\n")
        fp.write("    const char   *name;\n")
        fp.write("    int8_t        expected_label; /* 0=person, 1=no-person */\n")
        fp.write("} test_image_t;\n\n")

        fp.write("static const test_image_t test_images[] = {\n")
        for name, src, label in entries:
            disp = safe_ident(src.stem)[:24]
            fp.write(f'    {{ {name}, "{disp}", {label} }},\n')
        fp.write("};\n")
        fp.write(
            f"static const int test_images_count = "
            f"(int)(sizeof(test_images)/sizeof(test_images[0]));\n\n"
        )
        fp.write("#endif /* TEST_IMAGES_H_ */\n")

    total_bytes = len(entries) * bytes_per_image
    print(
        f"wrote {args.out} — {len(entries)} images @ "
        f"{args.width}x{args.height}x{CHANNELS}, "
        f"{total_bytes} B total ({total_bytes/1024:.1f} KiB)"
    )


if __name__ == "__main__":
    main()
